# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 29bc08ceeb9e3b739ad2e4efc5ba16d198ecd5459ded9924d6fc72d5825c99e0bb551e065fb34ac2ac21a49fe9818d728aea8a314e74b21ee3ab7356fee098f3

test:
  secret_key_base: 6cc7dc9af3c31f3f3cc33f6eb6f2598cec4b7e4215758da7c8495ba1517d86c3d8d8ed787122daa5f763669418be1c674226d43b5ef8e976ba554256b3eed418

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
